name: uberblick
description: Uberblick

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.11.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.7
  sqflite: ^1.0.0
  path: any
  http: any
  cupertino_icons: ^1.0.2
  path_provider: ^1.6.14
  country_list_pick: ^1.0.0+3
  rflutter_alert: ^1.0.3
  device_apps: ^2.1.1
  google_fonts: ^1.1.0
  email_validator: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  qr_code_scanner: ^0.4.0

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/qrs/
    - assets/images/dashboard_score.png

  uses-material-design: true
